name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build:
    name: Build
    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
    
    - name: Setup VSTest.console.exe
      uses: darenm/Setup-VSTest@v1

    - name: Restore NuGet packages
      run: nuget restore DBTek.Crypto/DBTek.Crypto.csproj

    - name: Build the Project 
      run: msbuild DBTek.Crypto/DBTek.Crypto.csproj

    - name: Restore NuGet packages for Test
      run: nuget restore DBTek.Crypto/DBTek.Crypto.csproj

    - name: Build the Test Project 
      run: msbuild DBTek.Crypto.Test/DBTek.Crypto.Test.csproj
    
    - name: Execute Unit Tests
      run: vstest.console.exe **/*.Test.dll
