name: Net Framework CI

on: [push]

jobs:
  build:

    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: msbuild DBTek.Crypto.sln -p:Configuration=Release

